### ISSUE TITLE
使用spring test进行单元测试时，发现重复打印sql

### ISSUE THREAD

**Issue by w8y56f** [kookob/mybatis-log-plugin#57]
使用spring test进行单元测试时，发现重复打印sql（打印了2次）。但是如果通过http方式调用，正常打印1次。可以写个最简单的springboot测一下。使用的是2.1.1的插件，2.x的springboot。详细日志见附件
[issue_是markdown.log](https://github.com/kookob/mybatis-log-plugin/files/4402011/issue_.markdown.log)

**Comment by evanwangace** [comment]
复议，我也是买了插件的开发者。出现了一模一样的问题。
我的springboot版本。
```xml
   <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.2.1.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
```

下面是我的application.yml中关于mybatis和log的配置

```yml
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.evan.mall: INFO
  file:
    name: ${user.home}/.shopping-mall-service/logs
```
